<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath>$(SolutionDir)Output\$(Platform)\</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CefSharp.WinForms.NETCore" Version="120.1.110" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cys_Common\Cys_Common.csproj" />
  </ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Message Importance="high" Text="Removing other runtimes..." />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\alpine-x64&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\linux-arm&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\linux-arm64&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\linux-armel&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\linux-musl-x64&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\linux-x64&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\linux-x86&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\osx-x64&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\unix&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\win&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\win8-arm&quot; &gt; nul" />
		<Exec Command="rmdir /s /q &quot;$(OutputPath)runtimes\win-arm64&quot; &gt; nul" />
	</Target>
</Project>